version: "3.7"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:8080

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
